# Generated by Django 5.0.11 on 2025-03-12 13:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Plan Name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Description"),
                ),
                (
                    "price_monthly",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monthly Price"
                    ),
                ),
                (
                    "price_annual",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Annual Price"
                    ),
                ),
                (
                    "features",
                    models.JSONField(
                        default=dict,
                        help_text="JSON object defining plan features and limits",
                        verbose_name="Features",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Active")),
                (
                    "stripe_price_id_monthly",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Stripe Monthly Price ID",
                    ),
                ),
                (
                    "stripe_price_id_annual",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Stripe Annual Price ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
            ],
            options={
                "verbose_name": "Subscription Plan",
                "verbose_name_plural": "Subscription Plans",
                "ordering": ["price_monthly"],
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("trialing", "Trialing"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                            ("unpaid", "Unpaid"),
                            ("incomplete", "Incomplete"),
                            ("incomplete_expired", "Incomplete Expired"),
                        ],
                        default="active",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "interval",
                    models.CharField(
                        choices=[("month", "Monthly"), ("year", "Annual")],
                        default="month",
                        max_length=10,
                        verbose_name="Billing Interval",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Start Date"
                    ),
                ),
                (
                    "end_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="End Date"
                    ),
                ),
                (
                    "trial_end",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Trial End"
                    ),
                ),
                (
                    "stripe_customer_id",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Stripe Customer ID"
                    ),
                ),
                (
                    "stripe_subscription_id",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="Stripe Subscription ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Updated At"),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscriptions.subscriptionplan",
                        verbose_name="Subscription Plan",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscription",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "User Subscription",
                "verbose_name_plural": "User Subscriptions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UsageRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "record_type",
                    models.CharField(
                        choices=[
                            ("video_creation", "Video Creation"),
                            ("storage", "Storage Used"),
                            ("api_call", "API Call"),
                            ("download", "Download"),
                            ("publishing", "Publishing"),
                        ],
                        max_length=50,
                        verbose_name="Record Type",
                    ),
                ),
                (
                    "feature_key",
                    models.CharField(max_length=100, verbose_name="Feature Key"),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Value"
                    ),
                ),
                (
                    "reference_id",
                    models.CharField(
                        blank=True,
                        help_text="ID of the related object (e.g., video ID)",
                        max_length=100,
                        verbose_name="Reference ID",
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="Additional information about the usage",
                        verbose_name="Metadata",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="Recorded At"
                    ),
                ),
                (
                    "billing_period_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="Billing Period Start"
                    ),
                ),
                (
                    "billing_period_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Billing Period End"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Usage Record",
                "verbose_name_plural": "Usage Records",
                "ordering": ["-recorded_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "record_type", "billing_period_start"],
                        name="subscriptio_user_id_ce5ad3_idx",
                    ),
                    models.Index(
                        fields=["user", "feature_key"],
                        name="subscriptio_user_id_d6efe4_idx",
                    ),
                ],
            },
        ),
    ]
