# Generated by Django 5.0.11 on 2025-03-12 12:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="elevenlabs_api_key",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ElevenLabs API Key"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="monthly_usage",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Monthly Usage"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="openai_api_key",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="OpenAI API Key"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="preferences",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Preferences"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="social_tokens",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Social Media Tokens"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_end_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Subscription End Date"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_metadata",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Subscription Metadata"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_plan",
            field=models.CharField(
                choices=[
                    ("free", "Free"),
                    ("standard", "Standard"),
                    ("premium", "Premium"),
                ],
                default="free",
                max_length=50,
                verbose_name="Subscription Plan",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_start_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Subscription Start Date"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="subscription_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("trial", "Trial"),
                    ("cancelled", "Cancelled"),
                    ("expired", "Expired"),
                ],
                default="inactive",
                max_length=50,
                verbose_name="Subscription Status",
            ),
        ),
        migrations.CreateModel(
            name="APIUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("api_name", models.CharField(max_length=100, verbose_name="API Name")),
                ("endpoint", models.CharField(max_length=255, verbose_name="Endpoint")),
                (
                    "tokens_used",
                    models.IntegerField(default=0, verbose_name="Tokens Used"),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=4,
                        default=0.0,
                        max_digits=10,
                        verbose_name="Cost",
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(auto_now_add=True, verbose_name="Timestamp"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_usage",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "API Usage",
                "verbose_name_plural": "API Usage",
                "ordering": ["-timestamp"],
            },
        ),
    ]
