# Generated by Django 5.0.11 on 2025-02-04 18:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Media",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("audio", "Audio"),
                            ("image", "Image"),
                            ("document", "Document"),
                        ],
                        max_length=20,
                        verbose_name="File Type",
                    ),
                ),
                (
                    "file_url",
                    models.FileField(upload_to="media/", verbose_name="File URL"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(verbose_name="File Size in Bytes"),
                ),
                (
                    "duration",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Duration in Seconds"
                    ),
                ),
                (
                    "thumbnail_url",
                    models.URLField(
                        blank=True, null=True, verbose_name="Thumbnail URL"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_media",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media",
                "verbose_name_plural": "Media",
                "ordering": ["-created_at"],
            },
        ),
    ]
