# Generated by Django 5.0.11 on 2025-02-04 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0002_media"),
    ]

    operations = [
        migrations.RenameField(
            model_name="media",
            old_name="file_url",
            new_name="file",
        ),
    ]
