# Generated by Django 5.0.11 on 2025-03-13 08:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0004_alter_media_file_screen"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Script",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("content", models.TextField(verbose_name="Script Content")),
                (
                    "version",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Version Number"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("final", "Final"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("topic", models.CharField(max_length=255, verbose_name="Topic")),
                (
                    "audience",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Target Audience"
                    ),
                ),
                (
                    "tone",
                    models.CharField(blank=True, max_length=100, verbose_name="Tone"),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(
                        default=60, verbose_name="Duration in Seconds"
                    ),
                ),
                (
                    "additional_instructions",
                    models.TextField(
                        blank=True, verbose_name="Additional Instructions"
                    ),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="Metadata"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_scripts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "screen",
                    models.ForeignKey(
                        blank=True,
                        help_text="The screen/project this script is associated with",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scripts",
                        to="workspaces.screen",
                    ),
                ),
                (
                    "workspace",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scripts",
                        to="workspaces.workspace",
                    ),
                ),
            ],
            options={
                "verbose_name": "Script",
                "verbose_name_plural": "Scripts",
                "ordering": ["-created_at", "-version"],
                "unique_together": {("workspace", "title", "version")},
            },
        ),
    ]
