# Generated by Django 5.0.11 on 2025-03-15 06:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0005_script"),
    ]

    operations = [
        migrations.CreateModel(
            name="Channel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Channel Name")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "logo",
                    models.URLField(blank=True, null=True, verbose_name="Logo URL"),
                ),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Website"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "prompt_templates",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Prompt Templates"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="workspace",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                help_text="The channel this workspace is associated with",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workspaces",
                to="workspaces.channel",
            ),
        ),
    ]
