# Generated by Django 5.0.11 on 2025-03-15 09:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0006_channel_workspace_channel"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="images_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Status of image generation for this screen",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="screen",
            name="is_original",
            field=models.BooleanField(
                default=True,
                help_text="Whether this is an original screen or a translation",
            ),
        ),
        migrations.AddField(
            model_name="screen",
            name="language",
            field=models.CharField(
                default="en", help_text="Language of the screen content", max_length=10
            ),
        ),
        migrations.AddField(
            model_name="screen",
            name="original_screen",
            field=models.ForeignKey(
                blank=True,
                help_text="The original screen this is translated from",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="translations",
                to="workspaces.screen",
            ),
        ),
        migrations.AddField(
            model_name="screen",
            name="scene_data",
            field=models.JSONField(
                default=list, help_text="Extracted scene data from the script"
            ),
        ),
        migrations.AddField(
            model_name="screen",
            name="script",
            field=models.ForeignKey(
                blank=True,
                help_text="The script this screen is based on",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="screen_versions",
                to="workspaces.script",
            ),
        ),
        migrations.AddField(
            model_name="screen",
            name="video_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Status of video compilation for this screen",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="screen",
            name="voices_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("completed", "Completed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                help_text="Status of voice generation for this screen",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="ScreenLanguageVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("language", models.CharField(max_length=10)),
                (
                    "translation_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "original_screen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="language_versions",
                        to="workspaces.screen",
                    ),
                ),
                (
                    "translated_screen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="original_version",
                        to="workspaces.screen",
                    ),
                ),
            ],
            options={
                "verbose_name": "Screen Language Version",
                "verbose_name_plural": "Screen Language Versions",
                "unique_together": {("original_screen", "language")},
            },
        ),
    ]
