# Generated by Django 5.0.11 on 2025-03-16 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0007_screen_images_status_screen_is_original_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="screen",
            name="images_status",
        ),
        migrations.RemoveField(
            model_name="screen",
            name="is_original",
        ),
        migrations.RemoveField(
            model_name="screen",
            name="language",
        ),
        migrations.RemoveField(
            model_name="screen",
            name="original_screen",
        ),
        migrations.RemoveField(
            model_name="screen",
            name="scenes",
        ),
        migrations.RemoveField(
            model_name="screen",
            name="settings",
        ),
        migrations.RemoveField(
            model_name="screen",
            name="video_status",
        ),
        migrations.RemoveField(
            model_name="screen",
            name="voices_status",
        ),
        migrations.RemoveField(
            model_name="script",
            name="screen",
        ),
        migrations.RemoveField(
            model_name="workspace",
            name="channel",
        ),
        migrations.AddField(
            model_name="screen",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="screen_images",
                to="workspaces.media",
            ),
        ),
        migrations.AddField(
            model_name="screen",
            name="scene",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="screen",
            name="voice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="screen_voices",
                to="workspaces.media",
            ),
        ),
        migrations.AddField(
            model_name="script",
            name="channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="scripts",
                to="workspaces.channel",
            ),
        ),
        migrations.AddField(
            model_name="script",
            name="output_file",
            field=models.FileField(blank=True, null=True, upload_to="scripts/"),
        ),
        migrations.AlterField(
            model_name="channel",
            name="logo",
            field=models.FileField(
                blank=True, null=True, upload_to="", verbose_name="Logo"
            ),
        ),
        migrations.AlterField(
            model_name="screen",
            name="scene_data",
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name="ScreenLanguageVersion",
        ),
    ]
