# Generated by Django 5.0.11 on 2025-03-16 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workspaces", "0008_remove_screen_images_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="screen",
            name="status_data",
            field=models.JSONField(
                blank=True, default=dict, help_text="Status data for components"
            ),
        ),
    ]
