# Generated by Django 5.0.11 on 2025-03-24 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0009_screen_status_data"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screen",
            name="output_file",
            field=models.FileField(
                blank=True, max_length=500, null=True, upload_to="screens/"
            ),
        ),
    ]
