# Generated by Django 5.0.11 on 2025-03-24 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0010_alter_screen_output_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="script",
            name="output_file",
            field=models.FileField(
                blank=True, max_length=500, null=True, upload_to="scripts/"
            ),
        ),
    ]
