# Generated by Django 5.0.11 on 2025-03-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0011_alter_script_output_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screen",
            name="output_file",
            field=models.FileField(
                blank=True, max_length=5000, null=True, upload_to="screens/"
            ),
        ),
    ]
