# Generated by Django 5.0.11 on 2025-03-27 07:27

import backend.workspaces.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0014_idea"),
    ]

    operations = [
        migrations.AlterField(
            model_name="media",
            name="file",
            field=models.FileField(
                max_length=5000,
                upload_to=backend.workspaces.models.get_upload_path,
                verbose_name="File URL",
            ),
        ),
    ]
