# Generated by Django 5.0.11 on 2025-03-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0015_alter_media_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="screen",
            name="scene",
            field=models.IntegerField(default=0),
        ),
    ]
