# Generated by Django 5.0.11 on 2025-04-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workspaces", "0016_alter_screen_scene"),
    ]

    operations = [
        migrations.AddField(
            model_name="script",
            name="publishing_info",
            field=models.JSONField(
                default=dict,
                help_text='\n            Stores publishing information for different platforms.\n            Format: {\n                "youtube": {\n                    "status": "published",\n                    "url": "https://youtube.com/...",\n                    "published_date": "2024-03-20T10:00:00Z",\n                    "notes": "Performance notes..."\n                },\n                "instagram": {\n                    "status": "not_published",\n                    "url": null,\n                    "published_date": null,\n                    "notes": ""\n                },\n                ...\n            }\n        ',
                verbose_name="Publishing Information",
            ),
        ),
    ]
